Repository fnplus/Algorithms-Hacktoberfest, pull requests merged in 2019-10, with the labels that each got.

#161 Insertion sort java and README update
  README.md
  insertion_sort/java/InsertionSort.java
Labels: hacktoberfest

#164 Added Knapsack Greedy algorithm in Clang
  greedy/knapsack.c
Labels: hacktoberfest

#156 Create Quick_sort.cpp
  quick_sort/cpp/Quick_Sort.cpp
Labels: hacktoberfest

#167 Added Insertion Sort for Python
  insertion_sort/Python/insertionsort.py
Labels: enhancement, hacktoberfest

#173 BitonicSort
  BitonicSort/Java/BitonicSort.java
Labels: hacktoberfest

#172 Added Insertion Sort using C and Quick Sort using JS
  insertion_sort/c/insertionSort.c
  quick_sort/javascript/quickSort.js
Labels: hacktoberfest

#174 Add HeightBST.java
  binary_search/clang/binary_search.c
  trees/HeightBST.java
Labels: hacktoberfest

#176 Tower of hanoir python
  README.md
  towers_of_hanoi/python/hanoi.py
Labels: hacktoberfest

#175 Inorder_BST.py
  trees/binary_search_tree/Inorder_BST.py
Labels: hacktoberfest

#178 Added Merge Sort & Euclidean GCD using Javascript
  euclidean_gcd/javascript/euclidean_gcd.js
  merge_sort/javascript/mergeSort.js
Labels: hacktoberfest

#177 Implemented heap sort in C
  heap_sort/clang/heap_sort.c
Labels: hacktoberfest

#179 Added Merge Sort Algo in C
  merge_sort/clang/merge_sort.c
Labels: hacktoberfest

#181 Implemented Queue in C
  queue/clang/queue.c
Labels: hacktoberfest

#182 Implemented Counting Sort Algo using C
  counting_sort/clang/counting_sort.c
Labels: hacktoberfest

#183 Add a queue in javascript
  queue/javascript/queue.js
Labels: hacktoberfest

#184 Stack implementation
  stack/cpp/stack.cpp
Labels: hacktoberfest

#185 Tower Of Hanoi In CPP
  towers_of_hanoi/cpp/TowerOfHanoi.cpp
Labels: hacktoberfest

#188 Towers of Hanoi on C++
  towers_of_hanoi/clang/hanoi.cpp
Labels: hacktoberfest

#189 Create PreorderTraversalOfBinaryTree.java
  binary_search/java/PreorderTraversalOfBinaryTree.java
Labels: hacktoberfest

#190 Graph: Add depth first search
  depth_first_search/golang/dfs.go
  depth_first_search/golang/dfs_test.go
Labels: hacktoberfest

#191 Add insertion sort
  insertion_sort/golang/sort.go
  insertion_sort/golang/sort_test.go
Labels: hacktoberfest

#192 bogosort.php Added bogo sort in php
  bogo_sort/php/bogosort.php
Labels: hacktoberfest

#193 Adding the insertion sort in R
  insertion_sort/R/.RData
  insertion_sort/R/.Rhistory
  insertion_sort/R/insretion_sort.r
Labels: hacktoberfest

#194 added code for segment tree
  trees/segment_tree_sum_range.cpp
Labels: hacktoberfest

#195 Create SelectionSort.java
  selection sort/java/SelectionSort.java
Labels: hacktoberfest

#198 Added implementation of STACK using JS
  stack/javascript/stack.js
Labels: hacktoberfest

#196 Create interpolation Search
  interpolation Search
Labels: hacktoberfest

#199 Implemented selection sort in python
  selection_sort/clang/SELECT.C
  selection_sort/java/SelectionSort.java
  selection_sort/python/SelectionSort.py
  shell_sort/clang/SHELL.C
Labels: hacktoberfest

#202 pisano period c++
  pisano period/C++/PisanoPeriod.cpp
Labels: hacktoberfest

#203 Tree Traversals in CPP
  trees/traversals/cpp/treeTrav.cpp
Labels: hacktoberfest

#204 quicksort.hs: Add quicksort for haskell
  quick_sort/haskell/quicksort.hs
Labels: hacktoberfest

#208 Added fibonacci in cpp
  fibonacci/cpp/fibonacci.cpp
Labels: hacktoberfest

#209 Added heap sort in c#
  heap_sort/c#
Labels: hacktoberfest

#210 Added selection sort in cpp
  selection_sort/cpp
Labels: hacktoberfest

#211 Added dijsktra's shortest path algorithm in cpp
  greedy/dijsktra/dijsktra.cpp
Labels: hacktoberfest

#212 Create DiagonalTraversalTree.cpp
  trees/DiagonalTraversalTree.cpp
Labels: hacktoberfest

#213 Sieve_Of_Eratosthenes
  Sieve_Of_Eratosthenes/Sieve_Of_Eratosthenes.cpp
Labels: hacktoberfest

#215 Added Fibonacci in O(1) Space in CPP
  fibonacci/cpp/Fibonacci_O(1)space.cpp
Labels: hacktoberfest

#217 Added fibonacci in C#
  fibonacci/C#
Labels: hacktoberfest

#220 Added linear search in javaScript
  linear_search/javascript/linear_search.js
Labels: hacktoberfest

#221 Add BubbleSort Algorithm in Dart
  .DS_Store
  bubble_sort/.DS_Store
  bubble_sort/dart/bubbleSort.dart
Labels: hacktoberfest

#225 Heap Sort using JS
  heap_sort/javascript/heapSort.js
Labels: hacktoberfest

#229 Added Height Of BST for CPP
  trees/HeightOfBST.cpp
Labels: hacktoberfest

#231 post order traversal in java
  towers_of_hanoi/java/Tower.java
  trees/traversals/Java/btree_postorder.java
  trees/traversals/Java/btree_preorder.java
Labels: hacktoberfest

#169 Aa
  README.md
  linear_search/Linear.java
Labels: conflict, hacktoberfest

#232 PalindromeChecker
  palindrome_checker/Palindrome_checker.py
Labels: hacktoberfest

#233 Wave Sort in Python
  wave_sort/python/waveSort.py
Labels: hacktoberfest

#237 Luhn Algo in CPP
  luhn/cpp/luhn.cpp
Labels: hacktoberfest

#240 Pisano Period in Python
  pisano period/python/pisanoPeriod.py
Labels: hacktoberfest

#241 Palindrome Checker solution for Java
  palindrome_checker/java/PalindromeChecker.java
Labels: hacktoberfest

#244 Create btree_level_order
  trees/traversals/Java/btree_level_order
Labels: hacktoberfest

#285 adding depth first search java program
  depth_first_search/java/depthffs.java
Labels: hacktoberfest

#253 Add check palindrome algorithm in Dart
  palindrome_checker/checkPalinrome.dart
Labels: hacktoberfest

#254 Add selection sort algorithm in Dart
  selection_sort/.DS_Store
  selection_sort/dart/selectionSoft.dart
Labels: hacktoberfest

#255 Add heap sort algorithm in Dart
  heap_sort/.DS_Store
  heap_sort/dart/heapSort.dart
Labels: hacktoberfest

#256 Shell Sort implementation using Python
  shell_sort/python/ShellSort.py
Labels: hacktoberfest

#286 added interpolation search in clang,cpp,java and python
  interpolation search/clang/interpolationsearch.c
  interpolation search/cpp/interpolationsearch.cpp
  interpolation search/java/interpolationsearch.java
  interpolation search/python/interpolationsearch.py
Labels: hacktoberfest

#246 Create InvertBT
  trees/InvertBT
Labels: hacktoberfest

#257 Palindrome.cpp
  palindrome_checker/palindrome.cpp
Labels: hacktoberfest

#258 linearseach c code
  breath_first_search/java/bfs.java
  linear_search/c-line/linearsearch.c
  palindrome_checker/palin.java
  palindrome_checker/palindrome-check.cpp
Labels: hacktoberfest

#262 linear search python
  insertion_sort/Python/insertion_sort.py.txt
  linear_search/Python-linear/linear_search.py.txt
Labels: hacktoberfest

#263 Java palindrome checker
  palindrome_checker/palindrome-checker.java
Labels: hacktoberfest

#264 initial commiting
  depth_first_search/java/bst.java
Labels: hacktoberfest

#265 Selection Sort in C
  selection_sort/clang/SelectionSort.c
Labels: hacktoberfest

#259 first
  euclidean_gcd/java/euclidean_gcd_using_recursion.java
  palindrome_checker/palindrome_checker.java
Labels: hacktoberfest

#266 First commit
  fibonacci/cpp/fibonacci_explained.txt
Labels: hacktoberfest

#267 Linear search in python
  linear_search/linearsearch.py
Labels: hacktoberfest

#268 binarysearch.py
  binary_search/python/binarysearch.py
Labels: hacktoberfest

#269 Added dijsktra's Algorithm in java and python.
  greedy/dijsktra/dijsktra.java
  greedy/dijsktra/dijsktra.py
Labels: hacktoberfest

#271 Added Depth First Search code in Python and Java
  depth_first_search/java/dfs.java
  depth_first_search/python/dfs.py
Labels: hacktoberfest

#260 LinearSearch
  linear_search/c-line/lsearch.txt
Labels: hacktoberfest

#273 Added Breadth First Search in python and cpp
  breath_first_search/cpp/bfs.cpp
  breath_first_search/python/bfs.py
Labels: hacktoberfest

#274 Code for Linear Search in python and C
  linear_search/C/linear.c
  linear_search/python/linear.py
Labels: hacktoberfest

#275 Binary Search
  binary_search/cpp/BinarySearch2.cpp
  binary_search/java/BinarySearch2.java
Labels: hacktoberfest

#276 Heap
  min_heap/heap.cpp
Labels: hacktoberfest

#282 Create Disjoint set.java
  disjoint_set/disjoint_set.java
Labels: hacktoberfest

#283 Create kruskal's algorithm
  kruskal/kruskal.java
Labels: hacktoberfest

#284 Create tarjan's algorithm
  Tarjan's algorithm/Tarjan.java
Labels: hacktoberfest

#287 Luhn algorithm implementation in python
  luhn/python/luhn.py
Labels: hacktoberfest

#288 Bitonic sort in python
  BitonicSort/Python/bitonicsort.py
Labels: hacktoberfest

#289 Traversals python
  trees/traversals/python/Traversals.py
Labels: hacktoberfest

#292 Amount_of _divisors.py
  amount_divisors_of_one_number/amount_divisors_of_one_number.py
Labels: hacktoberfest

#293 Added Merge sort in C#
  merge_sort/C#
Labels: hacktoberfest

#295 Added Linear Search in C#
  linear_search/C#
Labels: hacktoberfest

#296 Added Selection Sort in C#
  selection_sort/C#
Labels: hacktoberfest

#302 Bucket sort Java
  bucket_sort/Java/Bucket_sort.java
Labels: hacktoberfest

#307 Amount of Divisors of a Number: Added No_of_Divisors.java file. The c…
  amount_divisors_of_one_number/No_of_Divisors.java
Labels: hacktoberfest

#308 Added bucket sort in c#
  bucket_sort/c#
Labels: hacktoberfest

#312 Implemented swap without extra variable..
  bubble_sort/cpp/bubble_sort.cpp
Labels: enhancement, hacktoberfest

#313 ShellSort.java
  shell sort/ShellSort.java
Labels: hacktoberfest

#314 Added Maximum Sum Subarray Problem in Python
  Maximum Contiguous Subarray Sum Kadane's Algorithm/maxsubarraysum.py
Labels: hacktoberfest

#316 Added quicksort in ruby
  quick_sort/ruby/quick_sort.rb
Labels: hacktoberfest

#315 BogoSort.java Add Bogo Sorting Algorithm
  bogo_sort/Java/BogoSort.java
Labels: hacktoberfest

#319 Insert,Delete,Intersection,Union,Equality of sets
  infix_calc/cpp/infixCalc.cpp
  set_operations/cpp/set_operations.cpp
Labels: hacktoberfest

#320 Added my commit (linkedlist)
  Contributor.md
  linkedlist/linkedlist.cpp
Labels: hacktoberfest

#321 added permutations of string
  dynamic_programming/permutations.py
Labels: hacktoberfest

#324 Create counting_sort.kt
  counting_sort/Kotlin/counting_sort.kt
Labels: hacktoberfest

#325 Create binary_search.kt
  binary_search/Kotlin/binary_search.kt
Labels: hacktoberfest

#327 Added merge sort in Kotlin
  merge_sort/Kotlin/merge_sort.kt
Labels: hacktoberfest

#326 Added quick sort in Kotlin
  quick_sort/Kotlin/quick_sort.kt
Labels: hacktoberfest

#329 python program to search for an element in a linked list using recursion
  linkedlist/python/LinkedList.py
Labels: hacktoberfest

#331 Created height.c
  trees/height/Clang/height.c
Labels: hacktoberfest

#323 Added detect_duplicates.kt
  detect duplicates/Kotlin/detect_duplicates.kt
Labels: hacktoberfest, question

#322 Factorial in Kotlin
  factorial/Kotlin/factorial.kt
Labels: hacktoberfest

#317 Added shell_sort using C#
  shell_sort/shell_sort.cs
Labels: hacktoberfest

#332 Created counting_sort.js and slightly modified README
  README.md
  counting_sort/javascript/counting_sort.js
Labels: enhancement, hacktoberfest

#333 Added binary search cpp
  binary_search/cpp/BINARYSE.CPP
  bubble_sort/cpp/BUBBLE_A.CPP
Labels: hacktoberfest

#335 added fencing algo
  dynamic_programming/painting fence.py
Labels: hacktoberfest

#337 tree bfs cpp
  breath_first_search/cpp/bfs_tree.cpp
  counting_sort/cpp/counting.cpp
  insertion_sort/cpp/INSERTIO.CPP
Labels: hacktoberfest

#338 Linear Queue added
  queues/cpp/Linear Queue.cpp
Labels: enhancement, hacktoberfest

#343 added stack 1darray cpp
  stack/cpp/STACK1D.CPP
Labels: enhancement, hacktoberfest

#348 added tree height cpp
  trees/height/cpp/ht.cpp
Labels: enhancement, hacktoberfest
